Use correct name when generating method which takes an error as an argument (#1706)
The name must be renamed `FooError` -> `FooException` to match transforms done
elsewhere.

Without the other changes the test changes failed with:

```
uniffi-fixture-proc-macro-fb98904aa2d05965/uniffi/fixture/proc_macro/uniffi_proc_macro.kt:819:26: error: unresolved reference: BasicError
    fun `takeError`(`e`: BasicError): UInt
                         ^
uniffi-fixture-proc-macro-fb98904aa2d05965/uniffi/fixture/proc_macro/uniffi_proc_macro.kt:878:35: error: unresolved reference: BasicError
    override fun `takeError`(`e`: BasicError): UInt =
                                  ^
```

We need to apply the renaming to arg lists too.

Fixes: #1637