Require at least clap v3.1
3.0 to <=3.0.14 do not work
It will fail with something like this:

    error[E0405]: cannot find trait `CommandFactory` in crate `clap`
       --> uniffi_bindgen/src/lib.rs:499:10
        |
    499 | #[derive(Parser)]
        |          ^^^^^^ not found in `clap`
        |
        = note: this error originates in the derive macro `Parser` (in Nightly builds, run with -Z macro-backtrace for more info)

This seems to have been fixed in 3.1
Changelog is here: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md#310---2022-02-16