Add http-headermap custom type fixture
`http::HeaderMap` is a multi-map so for simplicity we expose as a `sequence` of
headers.

This was broken by https://github.com/mozilla/uniffi-rs/pull/1661 which caused:

```
error: unexpected token
   --> /tmp/target/debug/build/uniffi-fixture-ext-types-http-headermap-2750e41fdae052ad/out/http_headermap.uniffi.rs:132:40
    |
132 | ::uniffi::custom_type!(r#HeaderMap, std::vec::Vec<r#HttpHeader>);
    |                                        ^
```